# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'monitor_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(578, 320)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 5, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.comboBox = QtWidgets.QComboBox(Form)
        self.comboBox.setObjectName("comboBox")
        self.horizontalLayout_2.addWidget(self.comboBox)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.gamma_r = QtWidgets.QDoubleSpinBox(Form)
        self.gamma_r.setMinimum(0.1)
        self.gamma_r.setMaximum(10.0)
        self.gamma_r.setSingleStep(0.1)
        self.gamma_r.setProperty("value", 1.0)
        self.gamma_r.setObjectName("gamma_r")
        self.horizontalLayout_3.addWidget(self.gamma_r)
        self.gamma_g = QtWidgets.QDoubleSpinBox(Form)
        self.gamma_g.setMinimum(0.1)
        self.gamma_g.setMaximum(10.0)
        self.gamma_g.setSingleStep(0.1)
        self.gamma_g.setProperty("value", 1.0)
        self.gamma_g.setObjectName("gamma_g")
        self.horizontalLayout_3.addWidget(self.gamma_g)
        self.gamma_b = QtWidgets.QDoubleSpinBox(Form)
        self.gamma_b.setMinimum(0.1)
        self.gamma_b.setMaximum(10.0)
        self.gamma_b.setSingleStep(0.1)
        self.gamma_b.setProperty("value", 1.0)
        self.gamma_b.setObjectName("gamma_b")
        self.horizontalLayout_3.addWidget(self.gamma_b)
        self.gridLayout.addLayout(self.horizontalLayout_3, 2, 0, 1, 1)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setObjectName("widget")
        self.gridLayout.addWidget(self.widget, 4, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        self.brightness = QtWidgets.QDoubleSpinBox(Form)
        self.brightness.setMaximum(1.0)
        self.brightness.setSingleStep(0.1)
        self.brightness.setProperty("value", 1.0)
        self.brightness.setObjectName("brightness")
        self.horizontalLayout_4.addWidget(self.brightness)
        self.gridLayout.addLayout(self.horizontalLayout_4, 3, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton.setText(_translate("Form", "Применить"))
        self.label_3.setText(_translate("Form", "Разрешение /  Частота:"))
        self.label_4.setText(_translate("Form", "Гамма R / G / B :"))
        self.label_5.setText(_translate("Form", "Яркость :"))
        self.label_2.setText(_translate("Form", "Устройство :"))
        self.label.setText(_translate("Form", "*device*"))
